## 6-е домашнее задание - Библиотека numpy
## Леонтьева Ксения НПМбд-01-19

<b>Срок до 2 июня 2022г. (включительно)</b>

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring_Python_2022</b>» в github в папку "<b>homework-6</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


In [1]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [5]:
A_1 = np.linspace(-1.3, 2.5, 65) # если ставить 64 - то сгенерируется 63 отрезка и 64 точки
print(A_1)

[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [7]:
import random
n = random.randint(1, 10)
print('Длина массива =',3*n)
A_2 = np.array([1,2,3] * n)
print(A_2)

Длина массива = 15
[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [8]:
A_3 = np.arange(1, 20, 2)
print(A_3)

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [9]:
A_4 = np.zeros((10,10))
A_4[:,::9] = 1
A_4[::9,:] = 1

print(A_4)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [10]:
A_5 = np.zeros((8,8))
A_5[::2,1::2] = 1
A_5[1::2,::2] = 1
print(A_5)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [8]:
import random
n = random.randint(1, 10)

def create_matrix(i,j):
    res = i + j
    return res
A_6 = np.fromfunction(create_matrix, (n, n))
print(n)
print(A_6)

9
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 8.  9. 10. 11. 12. 13. 14. 15. 16.]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [12]:
V1 = np.array([1,2,3])
V2 = np.array([3,2,1])
PV = np.dot(V1,V2)
print('Произведение')
print(PV)

Произведение
10


In [13]:
M = np.random.randint(1, 10, size=(3,3))
V1 = np.array([1,2,3])
PMV = np.dot(M,V1)
print('Матрица М')
print(M)
print('Произведение')
print(PMV)

Матрица М
[[1 9 7]
 [6 8 9]
 [2 6 7]]
Произведение
[40 49 35]


In [14]:
M1 = np.random.randint(1, 10, size=(3,3))
M2 = np.random.randint(1, 10, size=(3,3))
PM = np.dot(M1,M2)
print('Матрица М1')
print(M1)
print('Матрица М2')
print(M2)
print('Произведение')
print(PM)

Матрица М1
[[5 6 5]
 [6 8 4]
 [1 6 8]]
Матрица М2
[[1 7 6]
 [6 7 4]
 [9 7 9]]
Произведение
[[ 86 112  99]
 [ 90 126 104]
 [109 105 102]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [15]:
A_8 = np.arange(0,1.01,0.05)
print(A_8)
A_cos = np.cos((A_8))
print('Массив косинусов')
print(A_cos)
A_sin = np.sin((A_8))
print('Массив синусов')
print(A_sin)
print(' ')
print('Общий массив')
print(np.hstack([A_cos, A_sin]))

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]
Массив косинусов
[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309 0.54030231]
Массив синусов
[0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
 0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
 0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
 0.78332691 0.8134155  0.84147098]
 
Общий массив
[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309 0.54030231 0.         0.04997917 0.09983342
 0.14943813 0.19866933 0.24740396 0.29552021 0.34289781 0.38941834
 0.43496553 0.47942554 0.52268723 0.56

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [27]:
A = np.random.rand(3,5) * 4 - 1
print(A)

[[ 1.88103593 -0.69571426  1.15572783 -0.33353652  1.74987666]
 [ 0.83086692  1.69394685  2.81475339  2.48885395  1.49596496]
 [ 1.41559876 -0.42570317  1.42192237  2.90123963  1.56796746]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [28]:
sum_all = np.sum(A)
print('Сумма всех элементов =', sum_all)
sum_row = np.sum(A, axis = 1)
print('Суммы элементов в строках: ', sum_row)
sum_col = np.sum(A, axis = 0)
print('Суммы элементов в столбцах: ', sum_col)
print(' ')

mean_row = np.mean(A, axis = 1)
print('Средние значения строк: ', mean_row)
var_row = np.var(A, axis = 1)
print('Дисперсии строк: ', var_row)
std_row = np.std(A, axis = 1)
print('Стандартные отклонения строк: ', std_row)

Сумма всех элементов = 19.962800755522792
Суммы элементов в строках:  [3.75738964 9.32438607 6.88102505]
Суммы элементов в столбцах:  [4.12750161 0.57252941 5.39240359 5.05655706 4.81380908]
 
Средние значения строк:  [0.75147793 1.86487721 1.37620501]
Дисперсии строк:  [1.14154818 0.50522049 1.12260369]
Стандартные отклонения строк:  [1.06843258 0.71078864 1.05952994]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [29]:
A_new = (A - np.transpose([mean_row,]*1)) / (np.transpose([std_row,]*1))
print(A_new)

[[ 1.05721037 -1.35450025  0.3783579  -1.01551981  0.93445179]
 [-1.45473666 -0.24047988  1.33636939  0.87786538 -0.51901822]
 [ 0.0371804  -1.70066754  0.04314872  1.43935019  0.18098823]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [30]:
A_sort = A[np.argsort(A[:, 2])]
print('Матрица A_sort')
print(A_sort)

Матрица A_sort
[[ 1.88103593 -0.69571426  1.15572783 -0.33353652  1.74987666]
 [ 1.41559876 -0.42570317  1.42192237  2.90123963  1.56796746]
 [ 0.83086692  1.69394685  2.81475339  2.48885395  1.49596496]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [31]:
A_transp = np.transpose(A)
B = np.dot(A_transp,A)
C = np.dot(A,A_transp)
print('Матрица А')
print(A)
print('Матрица А транспонированная')
print(A_transp)
print('Матрица В')
print(B)
print('Матрица C')
print(C)

Матрица А
[[ 1.88103593 -0.69571426  1.15572783 -0.33353652  1.74987666]
 [ 0.83086692  1.69394685  2.81475339  2.48885395  1.49596496]
 [ 1.41559876 -0.42570317  1.42192237  2.90123963  1.56796746]]
Матрица А транспонированная
[[ 1.88103593  0.83086692  1.41559876]
 [-0.69571426  1.69394685 -0.42570317]
 [ 1.15572783  2.81475339  1.42192237]
 [-0.33353652  2.48885395  2.90123963]
 [ 1.74987666  1.49596496  1.56796746]]
Матрица В
[[ 6.23255586 -0.503844    6.5255226   5.54750347  6.75414147]
 [-0.503844    3.53469744  3.35866943  3.21296551  0.64918225]
 [ 6.5255226   3.35866943 11.28040668 10.74537018  8.4626816 ]
 [ 5.54750347  3.21296551 10.74537018 14.72283199  7.68863986]
 [ 6.75414147  0.64918225  8.4626816   7.68863986  7.75850144]]
Матрица C
[[ 8.53133627  5.42510687  6.37839545]
 [ 5.42510687 19.91493755 14.02380254]
 [ 6.37839545 14.02380254 15.08271961]]


Обе матрицы являются квадратными, имеют одинаковую сумму элементов по диагонали, симметричны относительно диагонали. Размер матрицы В 5x5, размер матрицы С 3x3

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [32]:
summ_for_B = np.trace(B)
summ_for_C = np.trace(C)
print('Сумма в B: ', summ_for_B)
print('Сумма в C: ', summ_for_C)

Сумма в B:  43.52899341994935
Сумма в C:  43.52899341994935


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


Детерминант матрицы А (выдаст ошибку, т.к. матрица А не квадратная, поэтому детерминант не определен)

In [34]:
det_A = np.linalg.det(A) 

Детерминант матриц B и C 

In [35]:
det_B = np.linalg.det(B) 
det_C = np.linalg.det(C) 

print('det_B = ', det_B)
print('det_C = ', det_C)

det_B =  9.178898270607375e-29
det_C =  601.1523560626896


Ранг матриц A, B и C

In [36]:
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)
rank_C = np.linalg.matrix_rank(C)

print('rank_A = ', rank_A)
print('rank_B = ', rank_B)
print('rank_C = ', rank_C)

rank_A =  3
rank_B =  3
rank_C =  3


Спектр матриц B и C

In [37]:
w_B,v_B = np.linalg.eig(B)
print('Собственные значения матрицы B')
print(w_B)

Собственные значения матрицы B
[ 3.43746557e+01  6.43787594e+00  2.71646174e+00  1.56988260e-15
 -4.21430079e-16]


In [38]:
w_C,v_C = np.linalg.eig(C)
print('Собственные значения матрицы C')
print(w_C)

Собственные значения матрицы C
[34.37465574  6.43787594  2.71646174]


Ненулевые собственные значения матриц B и C совпадают

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [3]:
np.random.seed(1032192920)
print('Вариант:',np.random.randint(10))

Вариант: 8


In [3]:
# Метод прямоугольников
step = 0.00000001
x = np.arange(0.75,2,step)
f = (1 / (np.sqrt(-2*x**2 + 3*x + 2)))
ans1 = np.sum(f[0:len(x)-1]) * step
print(ans1)

1.1106361863920058


In [4]:
# Метод трапеций
step1 = 0.00000001
x = np.arange(0.75,2,step1)
f = (1 / (np.sqrt(-2*x**2 + 3*x + 2)))
ans2 = step1 / 2 * (f[0] + 2 * np.sum(f[1:len(x) - 2]) + f[len(x)-1])
print(ans2)

1.1106346685223596


In [105]:
# Метод Симпсона
step2 = 0.00000001
x = np.arange(0.75,2,step2)
f = (1 / (np.sqrt(-2*x**2 + 3*x + 2)))
ans3 = step2 / 3 *(f[0] + 2 * np.sum(f[2:len(x) - 3 :2]) + 4 * np.sum(f[1:len(x) - 2:2]) + f[len(x)-1])
print(ans3)

1.1106277730541603


Аналитическое решение:
$\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}} = \int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt{2}\sqrt {1 + \frac {3}{2}x - x^2} }}} = \int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt{2}\sqrt {1 - (x^2 - \frac {3}{2}x } )}}} = \int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt{2}\sqrt {1 - (x^2 - 2 \cdot \frac {3}{4}x  + \frac {9}{16}) + \frac {9}{16}}}}} = \int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt{2}\sqrt {\frac {25}{16} - (x - \frac {3}{4})^2}}}} = \frac {1}{\sqrt{2}} \cdot {arcsin (\frac{4}{5} (x-\frac{3}{4}))} \Biggr|_{{3/4}}^{2} = \frac {1}{\sqrt{2}} \cdot {arcsin (1)} - \frac {1}{\sqrt{2}} \cdot {arcsin (0)} \approx 1.11072$ 




In [6]:
# Метод прямоугольников
step1 = 0.0000001
xa = np.arange(0.75,1.9999,step1)
f11 = (1 / (np.sqrt(-2*xa**2 + 3*xa + 2)))
ans11 = np.sum(f11[0:len(xa)-1]) * step1

step2 = 0.000000001
xb = np.arange(1.9999,1.99999999,step2)
f12 = (1 / (np.sqrt(-2*xb**2 + 3*xb + 2)))
ans12 = np.sum(f12[0:len(xb)-1]) * step2
print(ans11+ans12)

1.1106224256540194


In [20]:
# Метод трапеций
step1 = 0.00000001
xa = np.arange(0.75,1.99,step1)
f21 = (1 / (np.sqrt(-2*xa**2 + 3*xa + 2)))
ans21 = step1 / 2 * (f21[0] + 2 * np.sum(f21[1:len(xa) - 2]) + f21[len(xa)-1])

step2 = 0.00000001
xb = np.arange(1.99,1.99999999,step2)
f22 = (1 / (np.sqrt(-2*xb**2 + 3*xb + 2)))
ans22 = step2 / 2 * (f22[0] + 2 * np.sum(f22[1:len(xb) - 2]) + f22[len(xb)-1])
print(ans21+ans22)

1.1106011371471254


In [18]:
# Метод Симпсона
step1 = 0.0000001
xa = np.arange(0.75,1.5,step1)
f = (1 / (np.sqrt(-2*xa**2 + 3*xa + 2)))
ans31 = step1 / 3 *(f[0] + 2 * np.sum(f[2:len(xa) - 3 :2]) + 4 * np.sum(f[1:len(xa) - 2:2]) + f[len(xa)-1])

step2 = 0.00000001
xb = np.arange(1.5,1.99999999,step2)
f = (1 / (np.sqrt(-2*xb**2 + 3*xb + 2)))
ans32 = step2 / 3 *(f[0] + 2 * np.sum(f[2:len(xb) - 3 :2]) + 4 * np.sum(f[1:len(xb) - 2:2]) + f[len(xb)-1])
print(ans31+ans32)

1.1105880894876763
