## ПЯТОЕ ДОМАШНЕЕ ЗАДАНИЕ

### Выполнила: Леонтьева Ксения Андреевна
### Группа: НПМбд-01-19

In [22]:
import numpy as np
import scipy.linalg

**LU - разложение матрицы А** - это представление этой матрицы в виде произведения A = LU, где L - нижняя треугольная матрица, U - верхняя треугольная ступенчатая матрица.

Для реализации данного разложения необходима единичная матрица, которую мы мысленно приписываем к нашей исходной матрице с правой стороны и далее применяем метод Гаусса для этих матриц (параллельно). В данном случае исходная матрица обозначается U, а единичная - L.

Дополнительно введем еще одну единичную матрицу M, которая будет хранить коэффициенты от деления первого элемента под главной диагональю на элемент главной диагонали, взятые в противоположным знаком. Чтобы не вводить два цикла будем брать деление не поэлементно, а делить ту часть столбца (вектор), который находится под элементом главной диагонали на этот элемент (см. #1).

Затем нужно изменять наши исходную и единичную матрицы соответственно. Для этого необходимо прибавить сразу ко всем строчкам, которые находятся под строчкой (U[i]), содержащей текущий диагональный элемент, произведение этой строчки (U[i]) на транспонированную матрицу коэффициентов (часть матрицы M) для данного столбца (т.о., это произведение (поэлементное!) будет представлять собой матрицу той же размерности, что и матрица, содержащая ранее указанные "все строчки, находящиеся под строчкой с текущим диагональным элементом") (см. #2). Сложение и вычитание матриц также поэлементные. Единичная матрица преобразовывается аналогичным образом.

В результате чего, мы получим следующее соотношение между матрицами: LA = U. Чтобы прийти в соотношению A = LU, нужно получить из текущей матрицы L обратную (т.к. текущая квадратная матрица L невырожденная, то она имеет квадратную матрицу) (см. #3).

In [23]:
def LUrazl(U):
    n = len(U)
    M = np.eye(n)
    L = np.eye(n)
    for i in range (len(U)-1): 
        M[i+1:,i] = - U[i+1:,i] / U[i][i]                                 #1
        U[i+1:,:] = U[i] * np.transpose([M[i+1:,i],]*1) + U[i+1:,:]       #2
        L[i+1:,:] = L[i] * np.transpose([M[i+1:,i],]*1) + L[i+1:,:]
    L = np.linalg.inv(L)                                                  #3
    return L, U

In [24]:
U1 = np.array([[1.,2,3],[4,5,6],[7,8,10]])
L, U = LUrazl(U1)
print('Матрица L')
print(L)
print('Матрица U')
print(U)

Матрица L
[[ 1. -0. -0.]
 [ 4.  1. -0.]
 [ 7.  2.  1.]]
Матрица U
[[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  1.]]


## Решаем уравнение L  y = b

Так как матрица L ступенчатая с единицамим на главной диагонали, то для начала мы можем сразу найти нулевой элемент вектора y (в программе имена для y и b совпадают), затем каждый раз из правой части уравнения вычитать произведение соответствующей строки из матрицы L на вектор y (обозначенный как b, b[:i] будет давать для 1 строки элемент y0 (b0), а для 2 строки - y0 (b0) и y1 (b1)).

In [25]:
def Lyb(L, b):
    b[0] = b[0] / L[0][0]
    for i in range(1,len(b)):
        b[i] = b[i] - np.dot(L[i][:i], b[:i])
    return(b)

In [26]:
b = [5,2,3]
y = Lyb(L, b)
print(y)

[5.0, -18.0, 4.0]


## Решаем уравнение U  x = y

Решение данного уравнения аналогично решению предыдущего уравнения, только в данном случае, т.к. матрица U - верхняя треугольная, мы находим решение, идя снизу вверх, от строки с наибольшим индексом к строке с наименьшим индексом. При этом разность делим на соответствующий диагональный элемент, потому что в матрице U на диагонали не единицы, а различные числа.

In [27]:
def Uxy(U, y):
    y[-1] = y[-1] / U[-1][-1]
    for i in range(len(y)-2, -1, -1):
        y[i] = (y[i] - np.dot(U[i][i+1:], y[i+1:])) / U[i][i]
    return y

In [28]:
x = Uxy(U,y)
print('Ответ:')
print(np.round(x,8))

Ответ:
[-3. -2.  4.]


## LUP - РАЗЛОЖЕНИЕ

**LUP - разложение матрицы А** - это представление этой матрицы в виде PA = LU, где L - нижняя треугольная матрица, U - верхняя треугольная ступенчатая матрица, P - матрица перестановок.

Нахождение данного разложения осуществляется по аналогичному алгоритму, что и для LU-разложения, но при этом нам нужно менять строчки местами (выбираем наибольший по модулю ведущий элемент) и также ввести матрицу перестановок P, в которой строчки будут меняться параллельно с изменением матрицы U.

Для нахождения максимального по модулю ведущего элемента мы используем дополнительный массив c, который хранит индексы максимальных по модулю ведущих элементов в столбцах для конкретных матриц U[i:,i:], а чтобы выбрать из этого массива максимальный ведущий элемент по модулю для всей матрицы U, мы должны обращаться к нулевому элементу этого массива "плюс" текущее значение i. Если эта сумма больше текущего значения i, то меняем местами строки.

Как работает массив с:

In [29]:
Z = np.array([[1.,2,3],[4,-5,6],[7,8,10]])
q = len(Z)
N = np.eye(q)
for i in range(q-1):
    V = abs(Z[i:,i:])
    print('Исходная матрица')
    print(Z)
    print('')
    print('Модуль среза исходной матрицы')
    print(V)
    print('')
    c = np.argmax(V, axis = 0)
    print('Массив c (выводит индексы максимальных по модулю элементов в каждом столбце среза)')
    print(c)
    print('')
    print('Индекс максимального по модулю элемента в исходной матрице')
    print(c[0] + i)
    print('')
    if c[0] + i > i:
        
        d = np.copy(Z[i])
        Z[i] = Z[c[0]+i]
        Z[c[0]+i] = d

    N[i+1:,i] = - Z[i+1:,i] / Z[i][i]
    Z[i+1:,:] = Z[i] * np.transpose([N[i+1:,i],]*1) + Z[i+1:,:]


Исходная матрица
[[ 1.  2.  3.]
 [ 4. -5.  6.]
 [ 7.  8. 10.]]

Модуль среза исходной матрицы
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]]

Массив c (выводит индексы максимальных по модулю элементов в каждом столбце среза)
[2 2 2]

Индекс максимального по модулю элемента в исходной матрице
2

Исходная матрица
[[ 7.          8.         10.        ]
 [ 0.         -9.57142857  0.28571429]
 [ 0.          0.85714286  1.57142857]]

Модуль среза исходной матрицы
[[9.57142857 0.28571429]
 [0.85714286 1.57142857]]

Массив c (выводит индексы максимальных по модулю элементов в каждом столбце среза)
[0 1]

Индекс максимального по модулю элемента в исходной матрице
1



Итоговое разложение

In [30]:
def LUPrazl(U):
    n = len(U)
    M = np.eye(n)
    L = np.eye(n)
    P = np.eye(n)
    for i in range(n-1):
        V = abs(U[i:,i:])
        c = np.argmax(V, axis = 0)

        if c[0] + i > i:

            d = np.copy(U[i])
            U[i] = U[c[0]+i]
            U[c[0]+i] = d

            d = np.copy(L[i])
            L[i] = L[c[0]+i]
            L[c[0]+i] = d

            d = np.copy(P[i])
            P[i] = P[c[0]+i]
            P[c[0]+i] = d

        M[i+1:,i] = - U[i+1:,i] / U[i][i]
        U[i+1:,:] = np.round(U[i] * np.transpose([M[i+1:,i],]*1) + U[i+1:,:],8)
        L[i+1:,:] = L[i] * np.transpose([M[i+1:,i],]*1) + L[i+1:,:]
    L = np.linalg.inv(L)  
    L = np.dot(P,L)
    return L, U, P

In [31]:
U2 = np.array([[1.,2,3],[4,5,6],[7,8,10]])
L, U, P = LUPrazl(U2)
print('Матрица L')
print(L)
print('')
print('Матрица U')
print(U)
print('')
print('Матрица P')
print(P)
print('')

Матрица L
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

Матрица U
[[ 7.          8.         10.        ]
 [ 0.          0.85714286  1.57142857]
 [ 0.          0.         -0.5       ]]

Матрица P
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]



Проверим решение LUP с помощью библиотеки scipy:

In [32]:
A, B, C = scipy.linalg.lu (np.array([[1.,2,3],[4,5,6],[7,8,10]]))
print('Матрица L')
print(B)
print('')
print('Матрица U')
print(C)
print('')
print('Матрица P')
print(A)
print('')


Матрица L
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

Матрица U
[[ 7.          8.         10.        ]
 [ 0.          0.85714286  1.57142857]
 [ 0.          0.         -0.5       ]]

Матрица P
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]



## Решаем уравнение L y = P b

Решение аналогично решению уравнения L * y = b, только предварительно нужно домножить правую часть еще на матрицу P. 

In [33]:
def LyPb(L, P, b):
    right = np.dot(P, b)
    right[0] = right[0] / L[0][0]
    for i in range(1,len(right)):
        right[i] = (right[i] - np.dot(L[i][:i], right[:i])) / L[i][i]

    return(right)

In [34]:
b = [5,2,3]
y = LyPb(L, P, b)
print(y)

[ 3.          4.57142857 -2.        ]


Проверим решение этого уравнения с помощью библиотеки scipy:

In [35]:
Y = scipy.linalg.solve(L, np.dot(P,b))
print(Y)

[ 3.          4.57142857 -2.        ]


## Решаем уравнение U x = y

Решение аналогично решению уравнения U * x = y при LU-разложении.

In [36]:
def Uxy1(y, U):
    y[-1] = y[-1] / U[-1][-1]
    for i in range(len(y)-2, -1, -1):
        y[i] = (y[i] - np.dot(U[i][i+1:], y[i+1:])) / U[i][i]
    return y

In [37]:
x = Uxy1(y, U)
print('Ответ:')
print(np.round(x,8))

Ответ:
[-3.00000002 -1.99999999  4.        ]


Проверим решение этого уравнения с помощью библиотеки scipy:

In [38]:
W =scipy.linalg.solve(U,Y)
print(W)

[-3.00000002 -1.99999999  4.        ]


## Вывод

LU-разложение для произвольной квадратной невырожденной матрицы возможно не всегда, необходимо, чтобы в процессе решения не было деления на ноль, в противном случае выгоднее использовать LUP-разложение, отличие которого в том, что перед каждым шагом нахождения коэффициентов, необходимых для последующего сложения строк, предшествует операция перестановки местами двух строк соответствующей матрицы, обеспечивающая получение ненулевых ведущих элементов.